FROM oven/bun:1 AS build
WORKDIR /app
COPY bun.lock package.json ./
RUN bun install --ci
COPY . .
ARG VITE_API_BASE
ENV VITE_API_BASE=${VITE_API_BASE}
RUN bun run build

FROM nginx:stable
COPY nginx.k8s.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/ /usr/share/nginx/html/

