image:
  repository: "nvcr.io/nim/nvidia/llama-3.2-nv-embedqa-1b-v2"
  tag: latest
model:
  ngcAPISecret: ngc-api
persistence:
  enabled: true
  storageClass: "ebs-sc"
  accessMode: ReadWriteOnce
  stsPersistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
imagePullSecrets:
  - name: registry-secret
